---
name: build

permissions:
  contents: read

on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".bowerrc"
      - ".editorconfig"
      - ".git-blame-ignore-revs"
      - ".gitattributes"
      - ".github/CONTRIBUTING.md"
      - ".github/FUNDING.yml"
      - ".github/ISSUE_TEMPLATE.md"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".github/SECURITY.md"
      - ".gitignore"
      - "docker-compose.yml"
      - "LICENSE.md"
      - "README.md"
      - "requirements.php"
      - "Vagrantfile"

  push: *ignore-paths

jobs:
  codeception-PHP-7.4:
    uses: yiisoft/yii2-actions/.github/workflows/codeception.yml@master
    with:
      codeception-command: vendor/bin/codecept run Functional,Unit --env php-builtin
      coverage-driver: none
      extensions: dom, json, gd, imagick
      php-version: '["8.0","8.1","8.2","8.3","8.4","8.5"]'
  codeception:
    uses: yiisoft/yii2-actions/.github/workflows/codeception.yml@master
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      codeception-command: vendor/bin/codecept run --env php-builtin --coverage-xml
      coverage-file: tests/Support/output/coverage.xml
      extensions: dom, json, gd, imagick
      php-version: '["7.4"]'
