---
name: docker

permissions:
  contents: read

on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".bowerrc"
      - ".editorconfig"
      - ".git-blame-ignore-revs"
      - ".gitattributes"
      - ".github/CONTRIBUTING.md"
      - ".github/FUNDING.yml"
      - ".github/ISSUE_TEMPLATE.md"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".github/SECURITY.md"
      - ".gitignore"
      - "docker-compose.yml"
      - "LICENSE.md"
      - "README.md"
      - "requirements.php"
      - "Vagrantfile"

  push: *ignore-paths

jobs:
  apache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v6

      - name: Build and start containers.
        run: docker compose up -d --build --wait

      - name: Composer update.
        run: docker compose run --rm php composer update --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Codeception build.
        run: docker compose exec -T php vendor/bin/codecept build

      - name: Codeception tests.
        run: docker compose exec -T php vendor/bin/codecept run --env docker
